### ISSUE TITLE
Update to Flask v3.x

### ISSUE THREAD

**Issue by shirey** [x-atlas-consortia/ubkg-api#127]
This need to happen at the same time as [this same change in hm-ontology-api](https://github.com/x-atlas-consortia/hs-ontology-api/issues/95)

**Comment by ChuckKollar** [comment]
I have run the test script (tests/test_ubkg_api.sh -v l) using the 'main' branch of 'ubkg-api'.
The script is written in a manner in which it tells you what the results should be and you need to check
to make sure that is what is returned; so it is very noisy. Rather I would write this script so that the script
itself analyzes that output from the server and ONLY produces output if it detects an anomaly.
That being said, there is places where running the script before any changes to the project are made
and after changing 'pyproject.toml' and 'src/ubkg_api/requirements.txt' where 500 errors occur inconsistently.
That is sometimes the script produces what it is supposed to produce, and sometimes a 500 error.

**Comment by ChuckKollar** [comment]
PR: https://github.com/x-atlas-consortia/ubkg-api/pull/142
