### ISSUE TITLE
Modularize UBKG service

### ISSUE THREAD

**Issue by shirey** [x-atlas-consortia/ubkg-api#7]
Modularize the UBKG API service such that it can:
  - Run as a standalone service exposing the endpoints defined within it
  - Run as the core for another service which can extend the UBKG API.  This is meant to be similar to how the search-adapter framework can be reused in multiple services to extend the functionality.  We need support to include the UBKG API software in another service, either via inclusion as a library from PyPI or via a git sub-module (inclusion via PyPI, `pip install`, is preferred)
    - expose the endpoints defined in UBKG API
    - and expose additional endpoints available for use in the new service

**Comment by AlanSimmons** [comment]
@SamSedivy 

The repo is currently a copy of the [ubkg](https://github.com/dbmi-pitt/ubkg) repo, which contains source for all things ubkg. We have since separated components into different repos in x-atlas-consortia.

To limit this repo to just API stuff, you can remove:

folder | new repo
--|--
neo4j | ubkg-neo4j
user_guide | ubkg-docs
scripts | ubkg-etl
source_framework | ubkg-etl

In addition, the current README.md file at the root is actually for the entire UBKG, and has been moved to ubkg-docs. The READMEs for the api are in the api folder.
